# Generated by Django 3.1.12 on 2025-05-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_pat', '0002_auto_20250411_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='hospital_affiliation',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='license_number',
        ),
        migrations.AddField(
            model_name='medicalprofessional',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalprofessional',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalprofessional',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterModelTable(
            name='medicalprofessional',
            table=None,
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
